name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: SDL3
      run: |
        git clone https://github.com/libsdl-org/SDL.git
        cd SDL
        mkdir build
        cd build
        cmake ..
        make
        cmake --install
    - name: Configure CMake Dynamic
      run: |
        cd ${{ github.workspace }}
        cd SDL_dynamic
        mkdir build
        cd build
        cmake ..
    - name: Configure CMake Static
      run: |
        cd ${{ github.workspace }}
        cd SDL_static
        mkdir build
        cd build
        cmake ..
    - name: Build Dynamic
      # Build your program with the given configuration
      run: |
        cd ${{ github.workspace }}
        cd SDL_dynamic
        cd build
        make
      
    - name: Build Static
      # Build your program with the given configuration
      run: |
        cd ${{ github.workspace }}
        cd SDL_static
        cd build
        make

